version: '3.8'

services:
  db:
    image: postgres:13
    container_name: wallet_database
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - wallet_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: wallet_app
    container_name: wallet_app
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  wallet_db_data: